name: Test_Oracle_10min
on:
  schedule:
    # Se lancera à 10h55 UTC (soit 12h55 à Martigny)
    # On met 12h55 pour être sûr que GitHub ait le temps d'enregistrer le changement
    - cron: '55 10 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python weather_bot.py
