name: Meteo Matin
on:
  schedule:
    # 06h00 et 07h00 du matin (Heure Suisse/Paris)
    # Note : GitHub utilise l'heure UTC, donc 4,5 = 6h et 7h en été
    - cron: '0 4,5 * * *'
  workflow_dispatch: # Permet toujours de le lancer manuellement

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python weather_bot.py
