name: Meteo Matin
on:
  schedule:
    # 04:05 UTC = 06:05 Martigny (Heure d'été)
    # 05:05 UTC = 07:05 Martigny
    - cron: '15 12 * * *'
    - cron: '5 5 * * *'
  workflow_dispatch: # Garde ça pour pouvoir tester manuellement !

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python weather_bot.py
